app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */
Route::get('/', function () {
    return Redirect::to('Home');
});
Route::resource('Home', 'Reception\ReceptionController@index');
Route::resource('BackLogin', 'admin\BackLoginController@index');

//vvvvvvvvvvvvvvvvv auth link vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Route::group(['middleware' => ['auth', 'sessiontimeout']], function () {
    Route::get('BackHome', ['as' => 'BackHome.index', 'uses' => 'admin\BackLoginController@Home',function(){
        return view('BackHome');
    }]);
    Route::group(['middleware' => ['acl']], function () {
        //^^^^^^^^^^^^^^^^基礎資料
        //log管理
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        //服務公告管理
        Route::resource('BackAnnouncementInformation', 'admin\PublicInformation\BackAnnouncementInformationController');
        //公告分類管理
        Route::resource('BackAnnouncementInformationClass', 'admin\PublicInformation\BackAnnouncementInformationClassController');
        //活動花絮
        Route::resource('BackBanner', 'admin\PublicInformation\BackBannerController');
        //塔位查詢
        Route::resource('BackTowerSelect', 'admin\TowerSelect\BackTowerSelectController');
        //各類櫃位及牌位使用情形及數量統計  
        Route::resource('BackPaper', 'admin\Paper\BackPaperController');
        //各項收入統計
        Route::resource('BackPaperMoneySum', 'admin\Paper\BackPaperMoneySumController');
        //各項新增收入及退費金額統計
        Route::resource('BackPaperMoneyDetail', 'admin\Paper\BackPaperMoneyDetailSumController');
        //牌位查詢
        Route::resource('BackTombstoneSelect', 'admin\Select\BackTombstoneSelectController');
        Route::get('BackTombstoneSelectChangeSelect', ['as' => 'BackTombstone.ChangeSelect', 'uses' => 'admin\Select\BackTombstoneSelectController@change_select']);

        //櫃位查詢
        Route::resource('BackCabinet', 'admin\Select\BackCabinetController');
        //貴為查詢條件變動
        Route::get('BackCabinetSelect', ['as' => 'BackCabinet.ChangeSelect', 'uses' => 'admin\Select\BackCabinetController@change_select']);

        //圖片刪除
        Route::get('BackRemove', ['as' => 'BackRemove.remove', 'uses' => 'admin\RemoveFileController@remove_file']);

        //帳號管理
        Route::resource('BackUserManagement', 'admin\Management\BackUserManagementController');
        //role管理
        Route::resource('BackRole', 'admin\management\role\BackRoleController'); 
        //程式註冊
        Route::resource('BackRoleControls', 'admin\Management\role\BackRoleControlsController'); 
        //角色維護
        Route::resource('BackProgramRegistration', 'admin\System\BackProgramRegistrationController');
        //選單註冊
        Route::resource('BackMenuClass', 'admin\System\BackMenuClassController');
        //聯絡我們Banner
        Route::resource('BackContactBanner', 'admin\Page\BackContactBannerController');
        //首頁設定
        Route::resource('BackIndexConfig', 'admin\Page\BackIndexConfigController');
        //關於我們Banner
        Route::resource('BackAboutBanner', 'admin\Page\BackAboutBannerController');
        Route::resource('BackAbout', 'admin\Page\BackAboutController');
        Route::resource('BackPtfe', 'admin\Page\BackPtfeController');
        Route::resource('BackQaBanner', 'admin\Page\BackQaBannerController');
        Route::resource('BackQa', 'admin\Page\BackQaController');
        Route::resource('BackContactConfig', 'admin\Page\BackContactConfigController');
        Route::resource('BackNews', 'admin\Page\BackNewsController');

        Route::resource('BackProduct', 'admin\Product\BackProductController');
        Route::resource('BackProductSize', 'admin\Product\BackProductSizeController');
        Route::resource('BackOrder', 'admin\Order\BackOrderController');

        Route::resource('OrientationData', 'admin\Page\OrientationDataController');

        Route::get('OrientationData', ['as' => 'Admin.OrientationData', 'uses' => 'admin\Orientation\BackOrientationController@change_data']);
        Route::group(['namespace' => 'admin'], function () {
            Route::get('BackReturnList/ReturnCheck', ['as' => 'ReturnList.update', 'uses' => 'ReturnList\BackReturnListController@return_checkon']);
            Route::get('BackReturnList/CancelReturn', ['as' => 'ReturnList.update', 'uses' => 'ReturnList\BackReturnListController@cancel_return']);
        });

    });
});
//^^^^^^^^^^^^^^^^^ auth link ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Route::group(['prefix' => 'auth'], function () {
    //註冊
    Route::get('/register', ['as' => 'register.index', 'uses' => 'Auth\AuthController@getregister']);
    Route::post('/register', ['as' => 'register.process', 'uses' => 'Auth\AuthController@Postregister']);
});
//登入
Route::post('Login', ['as' => 'Auth.authenticate', 'uses' => 'Auth\AuthController@authenticate']);
//登出
Route::get('Logout', ['as' => 'BackLogin.Logout', 'uses' => 'admin\BackLoginController@Logout']);

//前台登入
Route::post('RLogin', ['as' => 'Reception.RLogin', 'uses' => 'Reception\ReceptionController@RLogin']);
//前台登出
Route::get('RLogout', ['as' => 'Reception.RLogout', 'uses' => 'Reception\ReceptionController@RLogout']);

Route::get('About', ['as' => 'Reception.About', 'uses' => 'Reception\ReceptionController@About']);
Route::get('News', ['as' => 'Reception.News', 'uses' => 'Reception\ReceptionController@News']);
Route::get('NewsDetail/{id?}', ['as' => 'Reception.NewsDetail', 'uses' => 'Reception\ReceptionController@NewsDetail']);
Route::get('Ptfe', ['as' => 'Reception.Ptfe', 'uses' => 'Reception\ReceptionController@Ptfe']);
Route::get('PtfeDetail/{id?}', ['as' => 'Reception.PtfeDetail', 'uses' => 'Reception\ReceptionController@PtfeDetail']);
Route::get('Product', ['as' => 'Reception.Product', 'uses' => 'Reception\ReceptionController@Product']);
Route::get('ProductList', ['as' => 'Reception.ProductList', 'uses' => 'Reception\ReceptionController@ProductList']);
Route::get('ProductDetail/{id}', ['as' => 'Reception.ProductDetail', 'uses' => 'Reception\ReceptionController@ProductDetail']);
Route::get('QA', ['as' => 'Reception.QA', 'uses' => 'Reception\ReceptionController@QA']);
Route::get('Contacts', ['as' => 'Reception.Contacts', 'uses' => 'Reception\ReceptionController@Contacts']);
Route::get('Checkout', ['as' => 'Reception.Checkout', 'uses' => 'Reception\ReceptionController@Checkout']);

Route::post('Done', ['as' => 'Reception.Done', 'uses' => 'Reception\ReceptionController@Done']);

Route::get('Forgot', ['as' => 'Reception.Forgot', 'uses' => 'Reception\ReceptionController@Forgot']);
Route::get('LoginPage', ['as' => 'Reception.LoginPage', 'uses' => 'Reception\ReceptionController@LoginPage']);
Route::get('Member', ['as' => 'Reception.Member', 'uses' => 'Reception\ReceptionController@Member']);
Route::post('MemberDataUpdate', ['as' => 'Reception.MemberDataUpdate', 'uses' => 'Reception\ReceptionController@MemberDataUpdate']);
Route::get('OrderDetail/{id}', ['as' => 'Reception.OrderDetail', 'uses' => 'Reception\ReceptionController@OrderDetail']);
Route::get('Registar', ['as' => 'Reception.Registar', 'uses' => 'Reception\ReceptionController@Registar']);
Route::get('ChangeLang', ['as' => 'Reception.ChangeLang', 'uses' => 'Reception\ReceptionController@ChangeLang']);
Route::post('Registar', ['as' => 'Reception.RegistarPost', 'uses' => 'Reception\ReceptionController@RegistarPost']);
Route::get('Cart', ['as' => 'Reception.Cart', 'uses' => 'Reception\ReceptionController@Cart']);
Route::get('AddCart', ['as' => 'Reception.AddCart', 'uses' => 'Reception\CartController@AddCart']);
Route::get('DelCart', ['as' => 'Reception.DelCart', 'uses' => 'Reception\CartController@DelCart']);
Route::get('EditQuantityCart', ['as' => 'Reception.EditQuantity', 'uses' => 'Reception\CartController@EditQuantity']);
Route::get('OAuthLogin/{type}', ['as' => 'Auth.oauthLogin', 'uses' => 'Auth\AuthController@oauthLogin']);
Route::get('OAuthCallback/{type}', ['as' => 'Auth.oauthCallback', 'uses' => 'Auth\AuthController@oauthCallback']);

app/Http/Controllers/Reception/CartController.php
<?php

namespace App\Http\Controllers\Reception;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Input;
use Mail;
use UploadHandler;
use DB;
use Vsmoraes\Pdf\Pdf;
use Excel;
use Session;
use Hash;
// use App\Support\SSCart;
use App\Http\Requests\MemberUpdateRequest;

class CartController extends Controller
{
    function __construct(Pdf $pdf) {
        if(!Session::has('lang')){
          Session::put('lang','zh');
        }
    }  
    protected $ModelName="App\User";
    protected $ProductTable="product";
    protected $ProductSizeTable="product_size";
    // 首頁
    public function AddCart()
    {
        // Session::clear();
        $data=Session::get('cart');
        //檢查購物車裡有無商品
        if(isset($data[Input::get('product_id')])){
            $data[Input::get('product_id')]['quantity']+=Input::get('quantity');
        }else{
            $data[Input::get('product_id')]=array('product_id'=>Input::get('product_id'),'quantity'=>(int)Input::get('quantity'),'price'=>Input::get('price'));
        }
        Session::put('cart',$data);
        return count($data);
    } 
    public function DelCart()
    {
        $data=Session::get('cart');
        unset($data[Input::get('product_id')]);
        Session::put('cart',$data);
        $this->TotelData();
        return json_encode($this->TotelData());
        
    }  
    public function EditQuantity()
    {
        $type=Input::get('type');
        $product_id=Input::get('product_id');
        $data=Session::get('cart');
        switch ($type) {
            case '1':
                $data[$product_id]['quantity']+=1;
                break;
            case '2':
                $data[$product_id]['quantity']-=1;
                break;
            default:
                break;
        }
        Session::put('cart',$data);
        return json_encode($this->TotelData($product_id));
    }
    public function TotelData($product_id=0)
    {
        $cart=Session::get('cart');
        $data=array();
        if($product_id!=0){
            $data['this_price']=$cart[$product_id]['price']*$cart[$product_id]['quantity'];
        }
        $data['total']=0;
        foreach($cart as $key =>$value){
            $data['total']+=$value['price']*$value['quantity'];
        }
        return $data;
    }
}

resources/views/reception/contacts.blade.php
@extends('layouts.reception.reception')
@section('style')
<link rel="stylesheet" href="{{asset('css/about.css')}}">
@stop
@section('content')
    <div id="main" class="content">
        <div class="contacts">
    <div class="banner wow fadeIn" data-wow-duration="2s" style="background-image: url({{asset('images/main.jpg')}});" title="">
    </div>
    <div class="container">
        <section>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-end wow fadeInLeft" data-wow-duration="2s">
                    <li class="breadcrumb-item"><a href="{{route('Home.index')}}">首頁</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="#">聯絡我們</a>
                    </li>
                </ol>
            </nav>
            <div class="row justify-content-around">
                <div class="col-lg-5 col-12 mb-md-0 mb-3 info wow fadeInLeft" data-wow-duration="2s">
                    <ul class="">
                        <li>
                            <span>地址</span>
                            <p>{{$contact_config->address}}</p>
                        </li>
                        <li>
                            <span>電話</span>
                            <p><a href="tel:{{$contact_config->tel}}">{{$contact_config->tel}}</a></p>
                        </li>
                        <li>
                            <span>傳真</span>
                            <p>{{$contact_config->fax}}</p>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6 col-12 wow fadeIn" data-wow-duration="2s">
                    <form id="contacts">
                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-12 col-form-label">姓名</label>
                            <div class="col-md-9 col-12">
                                <input type="text" class="cus-form" id="name" placeholder="*必填" required="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="tel" class="col-md-3 col-12 col-form-label spec">電話</label>
                            <div class="col-md-9 col-12">
                                <input type="tel" class="cus-form" id="tel" placeholder="*必填" required="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-md-3 col-12 col-form-label">電子郵件</label>
                            <div class="col-md-9 col-12">
                                <input type="email" class="cus-form" id="email" placeholder="*必填" required="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="msg" class="col-md-3 col-12 col-form-label">洽詢內容</label>
                            <div class="col-md-9 col-12">
                                <textarea class="cus-form" id="msg" placeholder="備註"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-12 col-form-label">驗證碼</label>
                            <div class="col-md-4 col-5">
                                <input type="text" class="cus-form" id="name" placeholder="*必填" required="">
                            </div>
                            <div class="col-md-5 col-7 pl-2">
                                <span style="display: inline-block; width: 150px; height: 40px; background: #eee;"></span>
                                <span class="verify">更換驗證碼</span>
                            </div>
                        </div>
                        <div class="text-right">
                            <input type="submit" class="btn btn-primary" name="send" value="確認送出">
                        </div>
                    </form>
                </div>
                <div class="col-12 wow fadeIn mt-4" data-wow-duration="2s">
                    <div id="map"></div>
                </div>
            </div>
        </section>
    </div>
</div>
    </div>
@stop
@section('script')
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB8W3IS9FqG8DvDR6ZsZ2xFGqDk5yfwR-c"></script>
    <script src="{{asset('js/google_map.js')}}"></script>
@stop

resources/views/reception/done.blade.php
@extends('layouts.reception.reception')
@section('style')
<link rel="stylesheet" href="{{asset('css/member.css')}}">
@stop
@section('content')
    <div id="main">
        <div class="cart done">
    <section>
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-end wow fadeInLeft" data-wow-duration="2s">
                    <li class="breadcrumb-item"><a href="{{route('Home.index')}}">首頁</a></li>
                    <li class="breadcrumb-item"><a href="">購物車</a></li>
                    <li class="breadcrumb-item"><a href="">填寫資料</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="#">完成訂單</a>
                    </li>
                </ol>
            </nav>
            <!-- 結帳步驟 -->
            <div class="checkout-nav">
                <div class="step active">
                    <span class="badge now">
                        <span class="text">1</span>
                    </span>
                    <span class="done name">購物車</span>
                </div>
                <div class="step active">
                    <span class="badge now">
                        <span class="text">2</span>
                    </span>
                    <span class="done name">填寫資料</span>
                </div>
                <div class="step active">
                    <span class="badge now">
                        <span class="text">3</span>
                    </span>
                    <span class="name">完成訂單</span>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10 col-12">
                    <h5>訂購完成！</h5>
                    <h6>訂單編號：<span>{{$order['no']}}</span></h6>
                    @foreach($cart as $key =>$value)
                    <div class="row justify-content-center cart-row">
                        <div class="col-md-5 col-12 cart-item">
                            <div class="pro-img" style="background-image: url({{asset('Upload/Product/'.$value['img'])}});">
                            </div>
                            <div class="description">
                                <div>{{$value['name']}}</div>
                                <span class="help-text">{{$value['size']}}</span>
                            </div>
                        </div>
                        <div class="col-md-4 col-6 cart-quantity">
                            <div class="s-price">
                                <span class="price">${{$value['price']}}</span>
                            </div>
                            <div class="quantity">
                                <span class="amount">{{$value['quantity']}}</span>
                            </div>
                        </div>
                        <div class="col-md-3 col-6 cart-action">
                            <div class="s-total">
                                <span class="price">{{$value['price']*$value['quantity']}}</span>
                            </div>
                        </div>
                    </div>
                    @endforeach
                    <div id="total">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td>小計：</td>
                                    <td class="price">
                                        <span>{{$order['total']}}</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>運費：</td>
                                    <td class="price">
                                        <span>{{$order['freight']}}</span>
                                    </td>
                                </tr>
                                <tr class="total">
                                    <td>合計：</td>
                                    <td class="price">
                                        <span>{{$order['total']+$order['freight']}}</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                        <div class="card mt-4 mb-4">
                            <div class="card-header">
                                訂單資訊
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><span>付款方式</span>
                                    @if($order['delivery_method']==1)
                                        <p>貨到付款</p>
                                    @elseif($order['delivery_method']==2)
                                        <p>線上刷卡</p>
                                    @elseif($order['delivery_method']==3)
                                        <p>銀行匯款</p>
                                    @endif
                                </li>
                                <li class="list-group-item"><span>收件地址</span>
                                    <p>{{$order['add']}}</p>
                                </li>
                                <li class="list-group-item"><span>訂購人姓名</span>
                                    <p>{{$order['name']}}</p>
                                </li>
                                <li class="list-group-item"><span>訂購人信箱</span>
                                    <p>{{$order['email']}}</p>
                                </li>
                                <li class="list-group-item"><span>訂購人電話</span>
                                    <p>{{$order['tel']}}</p>
                                </li>
                                <li class="list-group-item"><span>收件人名稱</span>
                                    <p>{{$order['recipient_name']}}</p>
                                </li>
                                <li class="list-group-item"><span>收件人信箱</span>
                                    <p>{{$order['recipient_email']}}</p>
                                </li>
                                <li class="list-group-item"><span>收件人電話</span>
                                    <p>{{$order['recipient_tel']}}</p>
                                </li>
                                <li class="list-group-item"><span>發票類型</span>
                                    @if($order['invoice_method']==1)
                                    <p>二聯式發票</p>
                                    @else
                                    <p>三聯式發票</p>
                                    @endif
                                </li>
                                <li class="list-group-item"><span>備註</span>
                                    <p>{{$order['ext']}}</p>
                                </li>
                            </ul>
                        </div>
                </div>
            </div>
            <div class="text-center">
                <a href="Home" class="btn btn-outline">回首頁</a>
            </div>
        </div>
    </section>
</div>
    </div>
@stop
@section('script')
<script src="js/jquery.twzipcode.min.js"></script>
<!-- Main JS -->
<script type="text/javascript">
$(document).ready(function() {
    $('#twzipcode').twzipcode({
        'detect': true
    });
    $('#invoice-method').change(function() {
        $('.inv-').hide();
        $('.inv-' + $(this).val()).show("slow");
    }).change();
});
</script>
@stop

resources/views/reception/news.blade.php
@extends('layouts.reception.reception')
@section('style')
    <link rel="stylesheet" href="{{asset('css/about.css')}}">
@stop
@section('content')
    <div id="main" class="content">
        <div class="news">
    <section>
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-end wow fadeInLeft" data-wow-duration="2s">
                    <li class="breadcrumb-item"><a href="{{route('Home.index')}}">首頁</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="#">最新資訊</a>
                    </li>
                </ol>
            </nav>
            <ul class="nav nav-tabs" id="news-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link @if(Input::get('type',1)==1) active show @endif" id="news-1-tab" data-toggle="tab" href="#news-1" role="tab" aria-controls="news-1" aria-selected="true">最新資訊</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @if(Input::get('type',1)==2) active show @endif"" id="news-2-tab" data-toggle="tab" href="#news-2" role="tab" aria-controls="news-2" aria-selected="false">展場資訊</a>
                </li>
            </ul>
            <div class="tab-content wow fadeIn" data-wow-duration="2s" id="news-tab-content">
                <div class="tab-pane fade @if(Input::get('type',1)==1) active show @endif" id="news-1" role="tabpanel" aria-labelledby="news-1-tab">
                    <div class="row justify-content-center news-item">
                        <div class="col-md-6 col-12 wow fadeInUp" data-wow-duration="2s">
                            @foreach($news_type1 as $key =>$value)
                            @if($key%2==0)
                            <div class="row no-gutters item align-items-center">
                                <div class="col-3 cover">
                                	<div class="img" style="background-image: url({{asset('Upload/News/'.$value->img)}});" title="">
                                	</div>
                                </div>
                                <div class="col-9 title">
                                    <a href="{{route('Reception.NewsDetail',[$value->id])}}">
                                        <span class="date">{{$value->date}}</span>
                                        <span class="news-title">{{$value->title}}</span>
                                    </a>
                                </div>
                            </div>
                            @endif
                            @endforeach
                        </div>
                        <div class="col-md-6 col-12 wow fadeInUp" data-wow-duration="2s">
                            @foreach($news_type1 as $key =>$value)
                            @if($key%2==1)
                            <div class="row no-gutters item align-items-center">
                                <div class="col-3 cover">
                                    <div class="img" style="background-image: url({{asset('Upload/News/'.$value->img)}});" title="">
                                    </div>
                                </div>
                                <div class="col-9 title">
                                    <a href="{{route('Reception.NewsDetail',[$value->id])}}">
                                        <span class="date">{{$value->date}}</span>
                                        <span class="news-title">{{$value->title}}</span>
                                    </a>
                                </div>
                            </div>
                            @endif
                            @endforeach
                        </div>
                            {!! $news_type1->appends(['type'=>1])->render() !!}
                    </div>
                </div>
                <div class="tab-pane fade @if(Input::get('type',1)==2) active show @endif" id="news-2" role="tabpanel" aria-labelledby="news-2-tab">
                    <div class="row justify-content-center news-item">
                        <div class="col-md-6 col-12 wow fadeInUp" data-wow-duration="2s">
                            @foreach($news_type2 as $key =>$value)
                            @if($key%2==0)
                            <div class="row no-gutters item align-items-center">
                                <div class="col-3 cover">
                                    <div class="img" style="background-image: url({{asset('Upload/News/'.$value->img)}});" title="">
                                    </div>
                                </div>
                                <div class="col-9 title">
                                    <a href="{{route('Reception.NewsDetail',[1])}}">
                                        <span class="date">{{$value->date}}</span>
                                        <span class="news-title">{{$value->title}}</span>
                                    </a>
                                </div>
                            </div>
                            @endif
                            @endforeach
                        </div>
                        <div class="col-md-6 col-12 wow fadeInUp" data-wow-duration="2s">
                            @foreach($news_type2 as $key =>$value)
                            @if($key%2==1)
                            <div class="row no-gutters item align-items-center">
                                <div class="col-3 cover">
                                    <div class="img" style="background-image: url({{asset('Upload/News/'.$value->img)}});" title="">
                                    </div>
                                </div>
                                <div class="col-9 title">
                                    <a href="{{route('Reception.NewsDetail',[1])}}">
                                        <span class="date">{{$value->date}}</span>
                                        <span class="news-title">{{$value->title}}</span>
                                    </a>
                                </div>
                            </div>
                            @endif
                            @endforeach
                        </div>
                            {!! $news_type2->appends(['type'=>2])->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
    </div>
@stop
@section('script')   
    <script type="text/javascript">
        $(document).ready(function() {
            $('.parallax-window').parallax({imageSrc: '{{asset('images/about/IMG_0652.jpg')}}'});
            $('.news-title').ellipsis({
                row: 2
            });
        });
    </script>
@stop

resources/views/reception/news_detail.blade.php
@extends('layouts.reception.reception')
@section('style')
    <link rel="stylesheet" href="{{asset('css/about.css')}}">
@stop
@section('content')
<div id="main" class="content">
    <div class="news">
        <section>
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-end wow fadeInLeft" data-wow-duration="2s">
                        <li class="breadcrumb-item"><a href="{{route('Home.index')}}">首頁</a></li>
                        <li class="breadcrumb-item"><a href="{{route('Reception.News')}}">最新資訊</a></li>
                        <li class="breadcrumb-item active" aria-current="page">
                            <a href="#">資訊內文</a>
                        </li>
                    </ol>
                </nav>
                <div class="row justify-content-center">
                    <div class="col-md-10 col-11 wow fadeInUp" data-wow-duration="2s">
                        <article class="news-de">
                            <h5 class="title">{{$news->title}}</h5>
                            <p class="date">{{$news->date}}</p>
                            <div class="img" style="background-image: url({{asset('Upload/News/'.$news->img)}});">
                            </div>
                            <div class="text">
                                {!! $news->content !!}
                            </div>
                        </article>
                        <div class="text-center">
                            <a href="{{route('Reception.News')}}" class="btn btn-outline">返回最新資訊</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
@stop
@section('script')   
@stop